### ISSUE TITLE
Energy bracketing without effect

### ISSUE THREAD

**Issue by emmacarli** [cta-observatory/cta-irf-scaling#3] opened 2019-09-05 09:05 UTC
The PDFs of energy migration ratio are each scaled by a constant, and therefore their mean and standard deviation are left unchanged. Simulations using the energy bracketed IRF are therefore also unchanged.
This was presented in an Analysis and Simulation Working Group [meeting](https://indico.cta-observatory.org/event/2381/). 

[Energy_Bracketing.pdf](https://github.com/cta-observatory/cta-irf-scaling/files/3578740/Energy_Bracketing.pdf)

**Comment by FrancaCassol** [comment] 2020-01-21 13:27
Dear @Humberto-MH, @levgenVovk,
is the present git version corrected from this issue? (or the correction is inside the pending in PR [https://github.com/cta-observatory/cta-irf-scaling/pull/4](https://github.com/cta-observatory/cta-irf-scaling/pull/4) )

**Comment by Humberto-MH** [comment] 2020-01-21 15:03
Dear @FrancaCassol thanks for pointing on this. Yes, the correction is inside the pending PR #4. 
Dear @IevgenVovk, Can we proceed with the merge?

**Comment by IevgenVovk** [comment] 2020-04-09 09:32
The merge is executed. I'm closing the issue thusly. Please feel free to re-open it if the problem is still not solved.

**Closed as completed** 2020-04-09 09:34 UTC
